const $=id=>document.getElementById(id);let D;const fmt=x=>Number(x).toFixed(3),pct=x=>(x*100).toFixed(1)+'%';const colors=['#005f9e','#a6256e','#007e6c','#0075b5','#6b7f8a'];
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function bars(id,items){const w=950,row=42,h=items.length*row+42,min=Math.min(0,...items.map(x=>x.value)),max=Math.max(.8,...items.map(x=>x.value))*1.07;const x=v=>290+(v-min)/(max-min)*590;let s=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(id)}">`;
 for(let v=0;v<=max;v+=.2)s+=`<line x1="${x(v)}" y1="12" x2="${x(v)}" y2="${h-28}" stroke="#ebe0da"/><text x="${x(v)}" y="${h-5}" font-size="13" fill="#6b7f8a">${v.toFixed(1)}</text>`;
 items.forEach((r,i)=>{const y=i*row+20;const color=r.color||colors[i%colors.length];s+=`<text x="0" y="${y+12}" font-size="15" fill="#00294b">${esc(r.label)}</text><rect x="${Math.min(x(0),x(r.value))}" y="${y}" width="${Math.abs(x(r.value)-x(0))}" height="20" fill="${color}"/><circle cx="${x(r.value)}" cy="${y+10}" r="3" fill="${color}"/><text x="${x(r.value)+7}" y="${y+15}" font-size="15" fill="#00294b">${fmt(r.value)}</text>`;});$(id).innerHTML=s+'</svg>';}
function chosen(group,model){return D.metrics.find(r=>r.stock===$('stock').value&&r.group===group&&r.model===model)}
function render(){const stock=$('stock').value,f=$('funds').value,t=$('trade').value;const recent=[['daily','Daily close-to-close'],['intraday','Hourly daytime only'],['realized','Hourly + overnight'],['blend','Daily / realized blend']].map(([m,l])=>({label:l,value:chosen('hourly',`${m}_${f}_${t}`).daily_r2}));bars('hourchart',recent);let r=chosen('hourly',`daily_${f}_${t}`);$('recentnote').textContent=`Daily tracking R²; ${r.start} to ${r.end}, ${r.sessions} measured returns. Identical target dates and ${t==='m'?'monthly':'quarterly'} trading.`;
 const ci=D.wpm_portfolio_bootstrap.find(x=>x.model===`realized_${f}_${t}`);$('bootstrap').textContent=stock==='WPM'&&ci?`Wheaton's paired squared-error change: ${pct(ci.sse_reduction)} reduction; three-month-block interval ${pct(ci.interval95[0])} to ${pct(ci.interval95[1])}. This recent sample is short.`:'';
 const longs=[['daily_ew','Daily recency-weighted control'],['daily126','Daily 126-session estimate'],['daytime','Daytime-only estimate'],['overnight','Overnight-only estimate'],['realized','Daytime + overnight covariance'],['blend','Daily / realized blend']].map(([m,l])=>({label:l,value:chosen('sessions',`${m}_${f}`).daily_r2}));bars('longchart',longs);r=chosen('sessions',`daily_ew_${f}`);$('longnote').textContent=`Daily tracking R²; ${r.start} to ${r.end}. Quarterly trades. Control replica CAGR ${pct(r.portfolio_cagr)}; stock ${pct(r.stock_cagr)}.`;
 const panel=D.pca.find(x=>x.panel===$('panel').value);const pc=panel.statistics.find(x=>x.stock===stock);if(pc){bars('pcachart',[{label:'Gold / silver / equities explanation',value:pc.baseline.tracking_r2},{label:'Add one peer residual component',value:pc.one_peer_pc.tracking_r2,color:'#a6256e'},{label:'Add three peer residual components',value:pc.three_peer_pcs.tracking_r2,color:'#a6256e'}]);$('pcanote').textContent=`${panel.start} to ${panel.end}; ${panel.sessions} sessions. One peer component removes ${pct(pc.residual_sse_reduction_pc1)} of baseline squared residual error. EXPLANATORY ONLY.`;}else{$('pcachart').innerHTML='';$('pcanote').textContent='This company is outside the selected peer panel. Select the fourteen-company panel for its original constituents.';}
 bars('assetchart',[2,4,6].map(k=>({label:`${k} extra-asset principal directions`,value:chosen('asset-pca',`asset_pca${k}`).daily_r2})));$('assetnote').textContent=[2,4,6].map(k=>`${k} directions: replica CAGR ${pct(chosen('asset-pca',`asset_pca${k}`).portfolio_cagr)}`).join('; ')+'. Same long-history dates as above.';
 const five=D.five_minute.find(x=>x.stock===stock);if(five.results.length){const nf=f==='metals'?2:3;const a=five.results.filter(x=>x.funds===nf);bars('fivechart',a.map(x=>({label:`${x.minutes===390?'Whole session':x.minutes+' minutes'} · gold exposure`,value:x.weights[0]})));$('fivenote').textContent=`Gold notional per starting equity. ${a[0].train_days} complete training sessions and ${a[0].test_days} later test sessions, through September 2026. Other fund exposures and all statistics are in the downloadable evidence. This diagnostic resets its starting account each session and excludes overnight holding profit.`;const n=five.overnight.find(x=>x.funds===nf);$('nightnote').textContent=`Separate overnight estimate: gold exposure ${n.weights[0].toFixed(2)}; later overnight explanatory R² ${fmt(n.test_metrics.tracking_r2)}. Session-block confidence intervals are retained in evidence.json.`;}else{$('fivechart').innerHTML='';$('fivenote').textContent=five.status;$('nightnote').textContent='';}
 $('rows').innerHTML=D.metrics.filter(x=>x.stock===stock).map(r=>`<tr><td>${esc(r.group+' / '+r.model)}</td><td>${r.start}–${r.end}</td><td>${fmt(r.daily_r2)}</td><td>${fmt(r.monthly_r2)}</td><td>${pct(r.portfolio_cagr)}</td><td>${pct(r.stock_cagr)}</td></tr>`).join('');
 const p=new URLSearchParams();if(stock!=='WPM')p.set('stock',stock);if(f!=='metals')p.set('funds',f);if(t!=='m')p.set('trade',t);if($('panel').value!=='original7')p.set('panel',$('panel').value);history.replaceState(null,'',p.toString()?'#'+p.toString():location.pathname+location.search);
}
async function init(){D=window.EVIDENCE||await fetch('evidence.json').then(r=>{if(!r.ok)throw Error('Evidence failed to load');return r.json()});$('stock').innerHTML=D.companies.map(c=>`<option value="${c.ticker}">${esc(c.name)} (${c.ticker})</option>`).join('');const p=new URLSearchParams(location.hash.slice(1));for(const [k,def]of [['stock','WPM'],['funds','metals'],['trade','m'],['panel','original7']]){$(k).value=p.get(k)||def;if(!$(k).value)$(k).value=def;$(k).onchange=render;}const w=D.pca.find(x=>x.panel==='original7').statistics.find(x=>x.stock==='WPM');$('lead').textContent=`For Wheaton, one peer residual factor raises daily explanatory R² from ${fmt(w.baseline.tracking_r2)} to ${fmt(w.one_peer_pc.tracking_r2)} over the longer diagnostic period. Permitted-asset portfolios do not reproduce that gain.`;render();window.addEventListener('hashchange',()=>{for(const k of ['stock','funds','trade','panel']){const a=new URLSearchParams(location.hash.slice(1)).get(k);if(a)$(k).value=a;}render()});window.READY=true;}
init().catch(e=>{$('lead').textContent=e.message;window.APP_ERROR=e.message;});
