'use strict';
const D=window.GOLD_EVIDENCE,$=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
const palette=['#005f9e','#007e6c','#a6256e','#b8860b'];let selected=new Set(['WPM']);
const fmt=(n,d=3)=>Number.isFinite(n)?n.toFixed(d):'—',pct=n=>Number.isFinite(n)?(100*n).toFixed(1)+'%':'—';
const make=(tag,attrs={},text='')=>{const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text)e.textContent=text;return e};
function option(el,v,t){const o=document.createElement('option');o.value=v;o.textContent=t;el.append(o)}
D.companies.forEach(c=>option($('stock'),c.ticker,c.name+' ('+c.ticker+')'));
D.models.forEach(c=>option($('model'),c.id,c.label));$('stock').value='WPM';$('model').value='conditional_options_daily';
D.companies.forEach(c=>{const label=document.createElement('label');label.style.color=c.color;const check=document.createElement('input');check.type='checkbox';check.value=c.ticker;check.checked=selected.has(c.ticker);check.addEventListener('change',()=>{check.checked?selected.add(c.ticker):selected.delete(c.ticker);render();});label.append(check,document.createTextNode(c.ticker));$('companies').append(label)});
function state(){return {stock:$('stock').value,cadence:$('cadence').value,model:$('model').value,horizon:$('horizon').value,startyear:$('startyear').value,endyear:$('endyear').value,stride:$('stride').value,companies:[...selected].join(',')}}
function loadstate(){const p=new URLSearchParams(location.hash.slice(1));for(const id of ['stock','cadence','model','horizon','startyear','endyear','stride'])if(p.has(id)){const v=p.get(id);if($(id).tagName==='INPUT'||[...$(id).options].some(o=>o.value===v))$(id).value=v}if(p.has('companies'))selected=new Set(p.get('companies').split(',').filter(x=>D.paths[x]));document.querySelectorAll('#companies input').forEach(e=>e.checked=selected.has(e.value))}
loadstate();
function frame(id,title,xmin,xmax,ymin,ymax,w=950,h=340,xlabel='',ylabel=''){
 w=Math.max(340,Math.min(w,$(id).clientWidth||w));const svg=make('svg',{viewBox:`0 0 ${w} ${h}`,role:'img','aria-label':title});$(id).replaceChildren(svg);const L=65,R=30,T=w<600?85:25,B=57;
 if(xmin===xmax)xmax=xmin+1;if(ymin===ymax)ymax=ymin+1;
 const X=x=>L+(x-xmin)/(xmax-xmin)*(w-L-R),Y=y=>h-B-(y-ymin)/(ymax-ymin)*(h-T-B);
 for(let i=0;i<=4;i++){let x=xmin+(xmax-xmin)*i/4,y=ymin+(ymax-ymin)*i/4;svg.append(make('line',{x1:L,y1:Y(y),x2:w-R,y2:Y(y),stroke:'#dce5ec'}),make('text',{x:L-9,y:Y(y)+5,'text-anchor':'end','font-size':13,fill:'#6b7f8a'},ylabel.includes('R²')?fmt(y,2):pct(y)),make('text',{x:X(x),y:h-B+24,'text-anchor':'middle','font-size':13,fill:'#6b7f8a'},xlabel==='Year'?String(Math.round(x)):pct(x)));}
 svg.append(make('text',{x:w/2,y:h-7,'text-anchor':'middle','font-size':14,fill:'#00294b'},xlabel),make('text',{x:12,y:15,'font-size':14,fill:'#00294b'},ylabel));return {svg,X,Y,w,h};
}
function line(id,title,dates,series,ylabel){let vals=series.flatMap(s=>s.values).filter(Number.isFinite);let lo=Math.min(...vals),hi=Math.max(...vals);let pad=Math.max((hi-lo)*.08,.05);const f=frame(id,title,+dates[0].slice(0,4),+dates.at(-1).slice(0,4)+.75,lo-pad,hi+pad,950,340,'Year',ylabel);
 series.forEach((s,k)=>{let points=s.values.map((v,i)=>`${f.X(+dates[i].slice(0,4)+(+dates[i].slice(5,7)-1)/12)},${f.Y(v)}`).join(' ');f.svg.append(make('polyline',{points,fill:'none',stroke:s.color||palette[k],'stroke-width':2}));f.svg.append(make('text',{x:f.w<600?75:85+k*235,y:f.w<600?20+k*20:20,'font-size':13,fill:s.color||palette[k]},s.name));});
}
function tracking(stock,suffix){const names=['conditional_rates_daily','conditional_rates_daily_priority','conditional_rates_balanced'];if($('model').value.includes('options'))names.splice(0,3,'conditional_options_daily','conditional_options_daily_priority','conditional_options_balanced');const rows=names.map(x=>D.metrics.find(m=>m.stock===stock&&m.model===x+suffix));const fields=['daily_r2','r2_1m','r2_3m','r2_12m','r2_36m','r2_60m'];let vals=rows.flatMap(z=>fields.map(k=>z[k])).filter(Number.isFinite);const min=Math.min(0,...vals)-.07,max=Math.max(1,...vals)+.07;const width=Math.max(340,Math.min(950,$('tracking').clientWidth));const svg=make('svg',{viewBox:`0 0 ${width} 330`,role:'img','aria-label':'Tracking R squared across horizons'});$('tracking').replaceChildren(svg);const X=i=>65+i*(width-100)/5,Y=v=>265-(v-min)/(max-min)*(width<600?165:215);
 for(let i=0;i<=4;i++){let v=min+(max-min)*i/4;svg.append(make('line',{x1:65,y1:Y(v),x2:width-25,y2:Y(v),stroke:'#dce5ec'}),make('text',{x:57,y:Y(v)+4,'text-anchor':'end','font-size':13},fmt(v,2)))}
 ['Daily','Month','Quarter','Year','3 years','5 years'].forEach((t,i)=>svg.append(make('text',{x:X(i),y:298,'text-anchor':'middle','font-size':14},t)));
 rows.forEach((z,k)=>{let points=fields.map((field,i)=>Number.isFinite(z[field])?`${X(i)},${Y(z[field])}`:'').filter(Boolean).join(' ');svg.append(make('polyline',{points,fill:'none',stroke:palette[k],'stroke-width':2}));fields.forEach((field,i)=>{if(Number.isFinite(z[field])){let c=make('circle',{cx:X(i),cy:Y(z[field]),r:4,fill:palette[k]});c.append(make('title',{},`${['Daily only','80/10/10','50/25/25'][k]} · ${field}: ${fmt(z[field])}`));svg.append(c)}});svg.append(make('text',{x:width<600?75:80+k*260,y:width<600?20+k*20:20,'font-size':13,fill:palette[k]},['Daily only','80/10/10','50/25/25'][k]));});
 const daily=rows[0],bal=rows[2];$('tradeoff').textContent=`For ${stock}, changing to 50/25/25 moves daily tracking R² from ${fmt(daily.daily_r2)} to ${fmt(bal.daily_r2)}, and annual R² from ${fmt(daily.r2_12m)} to ${fmt(bal.r2_12m)}. These are later outcomes, not training fit.`;
}
function scatter(id,model,title){let points=[],h=+$('horizon').value,stride=$('stride').value==='h'?h:+$('stride').value;
 for(const stock of selected){const p=D.paths[stock],x=p.runs[model],y=p.stock;if(!x)continue;const c=D.companies.find(z=>z.ticker===stock);for(let a=0;a+h<p.dates.length;a+=stride){let b=a+h;if(+p.dates[a].slice(0,4)<+$('startyear').value||+p.dates[b].slice(0,4)>+$('endyear').value)continue;points.push({stock,start:p.dates[a],end:p.dates[b],x:x[b]/x[a]-1,y:y[b]/y[a]-1,color:c.color});}}
 if(!points.length){$(id).textContent='No complete windows for these settings.';return {n:0,wins:0}}
 let all=points.flatMap(p=>[p.x,p.y]);let lo=Math.min(0,...all),hi=Math.max(0,...all),pad=Math.max((hi-lo)*.06,.05);const f=frame(id,title,lo-pad,hi+pad,lo-pad,hi+pad,540,370,'Portfolio total return','Stock total return');f.svg.append(make('line',{x1:f.X(lo-pad),y1:f.Y(lo-pad),x2:f.X(hi+pad),y2:f.Y(hi+pad),stroke:'#6b7f8a','stroke-dasharray':'5 5'}));
 points.forEach(p=>{const c=make('circle',{cx:f.X(p.x),cy:f.Y(p.y),r:3.4,fill:p.color,opacity:.62,tabindex:0});const t=`${p.stock} · ${p.start} to ${p.end}\nPortfolio ${pct(p.x)} · stock ${pct(p.y)}\nStock minus portfolio ${(100*(p.y-p.x)).toFixed(1)} pp`;c.append(make('title',{},t));c.addEventListener('pointerenter',e=>{const tip=$('tooltip');tip.textContent=t;tip.style.whiteSpace='pre-line';tip.style.display='block';tip.style.left=Math.min(e.clientX+8,innerWidth-310)+'px';tip.style.top=Math.min(e.clientY+8,innerHeight-100)+'px'});c.addEventListener('pointerleave',()=>{$('tooltip').style.display='none'});f.svg.append(c)});return {n:points.length,wins:points.filter(p=>p.y>p.x).length};
}
function render(){$('tooltip').style.display='none';const stock=$('stock').value,suffix='_'+$('cadence').value,model=$('model').value+suffix,m=D.metrics.find(z=>z.stock===stock&&z.model===model),p=D.paths[stock],exp=D.exposures[stock][model].map(row=>Object.fromEntries(D.exposure_fields.map((key,i)=>[key,row[i]]))); $('sample').textContent=`${m.start}–${m.end} · ${m.sessions.toLocaleString()} daily return observations · ${m.decisions} scheduled decisions.`;
 $('cards').replaceChildren();[['Daily tracking R²',fmt(m.daily_r2)],['Annual tracking R²',fmt(m.r2_12m)],['Replica CAGR',pct(m.replica_cagr)],['Stock CAGR',pct(m.stock_cagr)]].forEach(([label,value])=>{let e=document.createElement('div');e.className='card';let strong=document.createElement('strong');strong.textContent=value;let span=document.createElement('span');span.textContent=label;e.append(strong,span);$('cards').append(e)});
 $('definition').textContent=`Realized annualized daily volatility: replica ${pct(m.replica_vol)}, stock ${pct(m.stock_vol)}. Average option premium ${pct(m.mean_option_premium)}; average absolute Treasury weight ${pct(m.mean_abs_rates_weight)}. Higher fees reduce replica CAGR to ${pct(m.stress_replica_cagr)}.`;
 tracking(stock,suffix);const uncertainty=D.wpm_bootstrap.filter(z=>z.new===model);$('uncertainty').textContent=stock==='WPM'&&uncertainty.length?uncertainty.map(z=>`${z.horizon_months===0?'Daily':'Annual'} squared-error reduction versus ${D.models.find(v=>v.id===z.base.slice(0,-2)).label}: ${pct(z.sse_reduction)}; 95% block interval ${pct(z.interval95[0])} to ${pct(z.interval95[1])} (${z.block_months}-month blocks).`).join(' ')+' These intervals condition on fitted paths and omit model-search uncertainty.':'Paired uncertainty is reported for Wheaton’s specified model additions; no interval is inferred by pooling unequal company histories.';line('wealth','Paid cumulative total return',p.dates,[{name:'Owned stock',values:p.stock.map(v=>v-1),color:'#a6256e'},{name:'Selected replica',values:p.runs[model].map(v=>v-1),color:'#005f9e'}],'Cumulative return');$('wealthnote').textContent=`One unit of starting capital becomes ${fmt(m.terminal_stock,2)} in the stock and ${fmt(m.terminal_replica,2)} in this replica. Financing, modeled fees and final liquidation are charged.`;
 line('exposure','Trade-date metal and Treasury exposures',exp.map(v=>v.date),[{name:'Gold delta',values:exp.map(v=>v.gold_delta)},{name:'Silver delta',values:exp.map(v=>v.silver_delta)},{name:'Treasury holding',values:exp.map(v=>v.treasury_weight)}],'Exposure / capital');const avg=k=>exp.reduce((a,b)=>a+b[k],0)/exp.length;$('exposurenote').textContent=`Average modeled gamma × spot: gold ${fmt(avg('gold_gamma'))}, silver ${fmt(avg('silver_gamma'))}. A one-point volatility rise has average modeled NAV sensitivity ${pct(avg('gold_vega_1pp'))} for gold and ${pct(avg('silver_vega_1pp'))} for silver. These are trade-date European-option sensitivities.`;
 const gold=scatter('goldscatter','volatility_gold'+suffix,'Stock versus past-volatility gold'),rep=scatter('modelscatter',model,'Stock versus selected replica');$('modelscattertitle').textContent=D.models.find(z=>z.id===$('model').value).label;$('scatterstats').textContent=`Gold chart: ${gold.n} windows, stock ahead in ${gold.wins}. Replica chart: ${rep.n} windows, stock ahead in ${rep.wins}.`;
 const tbody=$('results').querySelector('tbody');tbody.replaceChildren();D.metrics.filter(z=>z.stock===stock&&z.model.endsWith(suffix)).forEach(z=>{let tr=document.createElement('tr');if(z.model===model)tr.className='selected';let label=D.models.find(v=>v.id===z.model.slice(0,-2)).label;[label,fmt(z.daily_r2),fmt(z.r2_3m),fmt(z.r2_12m),fmt(z.r2_60m),pct(z.replica_cagr),pct(z.stress_replica_cagr),pct(z.mean_option_premium)].forEach(t=>{let td=document.createElement('td');td.textContent=t;tr.append(td)});tbody.append(tr)});
 const teacher=D.teacher.statistics.filter(z=>z.stock===stock);$('teacher').textContent=teacher.length?teacher.map(z=>`${z.family.replaceAll('_',' ')}: tracking R² ${fmt(z.tracking_r2)}`).join(' · ')+`. ${teacher[0].start}–${teacher[0].end}.`:'The longer seven-company explanatory diagnostic does not cover this company.';
 const previous=D.prior_v7.find(z=>z.stock===stock),annual=previous.same_date_metrics.horizons.find(z=>z.months===12);$('prior').textContent=`Earlier v7 metals-plus-equities account, quarterly trades on these dates: daily tracking R² ${fmt(previous.same_date_metrics.daily.r2)}, annual ${fmt(annual?.tracking_r2)}. The new models need not dominate that reference.${previous.sample_rebased?' The earlier account is rebased to this shorter sample, without fresh entry/exit fees.':''}`;
 $('audit').textContent=`${D.accounts} paid accounts and ${D.fit_decisions.toLocaleString()} decisions. All candidate results are retained. Samples and overlapping windows differ across companies.`;
 history.replaceState(null,'','#'+new URLSearchParams(state()).toString());
}
for(const id of ['stock','cadence','model','horizon','startyear','endyear','stride'])$(id).addEventListener('change',render);let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(render,100)});window.addEventListener('hashchange',()=>{loadstate();render()});render();window.READY=true;
