'use strict';
const $=id=>document.getElementById(id),dec=(v,n=3)=>Number.isFinite(v)?v.toFixed(n):'—',pct=(v,n=1)=>Number.isFinite(v)?(100*v).toFixed(n)+'%':'—';
let S,cache={},generation=0;
function table(id,heads,rows){$(id).innerHTML='<thead><tr>'+heads.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+x+'</td>').join('')+'</tr>').join('')+'</tbody>';}
function context(id){let c=$(id),box=c.getBoundingClientRect(),w=box.width,h=box.height,r=devicePixelRatio||1;c.width=w*r;c.height=h*r;let ctx=c.getContext('2d');ctx.scale(r,r);ctx.font='12px system-ui';return {ctx,w,h};}
function pathchart(dates,series){let {ctx,w,h}=context('path'),left=65,right=20,top=24,bottom=48,max=100;for(let s of series)for(let x of s.a)max=Math.max(max,x);max*=1.07;let X=i=>left+i/(dates.length-1)*(w-left-right),Y=x=>h-bottom-x/max*(h-top-bottom);ctx.fillStyle='#516774';ctx.strokeStyle='#e1e8ee';for(let i=0;i<=4;i++){let n=max*i/4;ctx.beginPath();ctx.moveTo(left,Y(n));ctx.lineTo(w-right,Y(n));ctx.stroke();ctx.textAlign='right';ctx.fillText(n.toFixed(0),left-8,Y(n)+4);}for(let s of series){ctx.strokeStyle=s.color;ctx.lineWidth=s.color==='#111111'?1.8:1.5;ctx.beginPath();s.a.forEach((x,i)=>{i?ctx.lineTo(X(i),Y(x)):ctx.moveTo(X(i),Y(x));});ctx.stroke();}ctx.fillStyle='#516774';ctx.textAlign='left';ctx.fillText(dates[0],left,h-15);ctx.textAlign='right';ctx.fillText(dates[dates.length-1],w-right,h-15);}
function scatter(x,y){let {ctx,w,h}=context('scatter'),l=65,r=20,t=25,b=50,low=0,high=0;for(let i=0;i<x.length;i++){low=Math.min(low,x[i],y[i]);high=Math.max(high,x[i],y[i]);}let gap=Math.max(.005,.07*(high-low));low-=gap;high+=gap;let X=v=>l+(v-low)/(high-low)*(w-l-r),Y=v=>h-b-(v-low)/(high-low)*(h-t-b);ctx.strokeStyle='#e1e8ee';ctx.fillStyle='#516774';for(let k=0;k<=4;k++){let a=low+(high-low)*k/4;ctx.beginPath();ctx.moveTo(X(a),t);ctx.lineTo(X(a),h-b);ctx.moveTo(l,Y(a));ctx.lineTo(w-r,Y(a));ctx.stroke();ctx.textAlign='center';ctx.fillText(pct(a,0),X(a),h-b+20);ctx.textAlign='right';ctx.fillText(pct(a,0),l-8,Y(a)+3);}ctx.strokeStyle='#71808a';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(X(low),Y(low));ctx.lineTo(X(high),Y(high));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#005f9e';ctx.globalAlpha=.4;for(let i=0;i<x.length;i++){ctx.beginPath();ctx.arc(X(x[i]),Y(y[i]),2.3,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;ctx.textAlign='left';ctx.fillText('Company return',l,14);ctx.textAlign='center';ctx.fillText('Portfolio return',w/2,h-8);}
function metric(run){let period=$('period').value;return $('cost').value==='stress'&&run.stress?run.stress[period]:run[period];}
async function load(ticker){if(!cache[ticker])cache[ticker]=(async()=>{let r=await fetch(ticker+'.json.gz');if(!r.ok)throw Error('Could not load company paths');return JSON.parse(await new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).text());})();return cache[ticker];}
async function update(){if(!S)return;let token=++generation,ticker=$('company').value,id=$('model').value,period=$('period').value,frequency=$('frequency').value,cost=$('cost').value;let c=S.companies.find(c=>c.company.ticker===ticker),base=c.runs.v4_gold_silver_quarterly,chosen=c.runs[id],bm=base[period],cm=metric(chosen);$('coverage').textContent=`${c.company.name} · ${cm.start} to ${cm.end} · ${cm[frequency].n.toLocaleString()} ${frequency} observations. ${S.models.find(m=>m.id===id).group}.`;
 table('comparison',['Model','Tracking R²','Regression R²','Return RMSE','Portfolio CAGR','Company CAGR'],[['Previous monthly-fit gold/silver',dec(bm[frequency].r2),dec(bm[frequency].regression_r2),pct(bm[frequency].rmse,2),pct(bm.portfolio_cagr),pct(bm.stock_cagr)],[S.models.find(m=>m.id===id).label,dec(cm[frequency].r2),dec(cm[frequency].regression_r2),pct(cm[frequency].rmse,2),pct(cm.portfolio_cagr),pct(cm.stock_cagr)]]);
 table('trials',['Candidate','Group','Tracking R²','Change','Return RMSE','Trades, full history'],S.models.map(model=>{let run=c.runs[model.id],m=metric(run),delta=m[frequency].r2-bm[frequency].r2;return [model.label,model.group,dec(m[frequency].r2),`<span class="${delta>=0?'good':'bad'}">${delta>=0?'+':''}${dec(delta)}</span>`,pct(m[frequency].rmse,2),run.trades??'Original'];}));
 table('events',['Date','Company return','Model return','Residual'],c.largest_residuals.map(e=>[e.date,pct(e.stock_return,2),pct(e.model_return,2),pct(e.residual,2)]));
 let dg=c.diagnostics;$('diagnostics').textContent=`Daily explanatory R² for the selected period: linear ${dec(dg[0].metrics[period].r2)}; quadratic ${dec(dg[1].metrics[period].r2)}. The ten largest error days account for ${pct(c.top10_error_share)} of the market model’s full-history squared error.`;
 let ld=chosen.latest_decision;$('decision').textContent=ld?`Latest scheduled decision, ${ld.entry}: ${ld.weights.map((w,i)=>((id.includes('calls')&&i>=ld.weights.length-2)?['Gold call','Silver call'][i-(ld.weights.length-2)]:['Gold','Silver','Broad equities','Long Treasuries','Oil','AUD','CAD'][i])+': '+dec(w,2)+'×').join(' · ')}. Fund values are NAV weights; calls are underlying-equivalent notionals. These are historical research exposures, not a trade recommendation.`:'Prior baseline: retained from the original study.';
 table('universe',['Company','Previous metals','Daily metals','Metals + equities','Chosen model'],S.companies.map(c=>[c.company.ticker,dec(c.runs.v4_gold_silver_quarterly[period][frequency].r2),dec(metric(c.runs.metals_ewq)[frequency].r2),dec(metric(c.runs.market_q)[frequency].r2),dec(metric(c.runs[id])[frequency].r2)]));
 try{let d=await load(ticker);if(token!==generation)return;let start=period==='full'?'0000-01-01':period==='confirmation'?'2020-01-01':'2023-01-01',first=d.dates.findIndex(x=>x>=start),dates=d.dates.slice(first),stock=d.stock_nav.slice(first),nav=(cost==='stress'&&d.runs[id].stress_nav?d.runs[id].stress_nav:d.runs[id].nav).slice(first),bn=d.runs.v4_gold_silver_quarterly.nav.slice(first);pathchart(dates,[{a:bn.map(x=>100*x/bn[0]),color:'#9da8ae'},{a:nav.map(x=>100*x/nav[0]),color:'#005f9e'},{a:stock.map(x=>100*x/stock[0]),color:'#111111'}]);let ix=frequency==='daily'?dates.map((_,i)=>i):[...new Set([0,...dates.map((dt,i)=>i===dates.length-1||dt.slice(0,7)!==dates[i+1].slice(0,7)?i:null).filter(x=>x!==null)])];let x=[],y=[];for(let k=1;k<ix.length;k++){let a=ix[k-1],b=ix[k];if(frequency==='daily'&&(Date.parse(dates[b])-Date.parse(dates[a]))/86400000>4)continue;x.push(nav[b]/nav[a]-1);y.push(stock[b]/stock[a]-1);}scatter(x,y);window.companyResearch.state={ticker,id,period,frequency,cost,points:x.length,metric:cm};$('status').textContent='26 portfolio rules · 20 companies · daily estimates, slow trading · all trial results retained';}catch(e){$('status').textContent=e.message;console.error(e);}}
async function init(){try{let r=await fetch('summary.json');S=await r.json();S.companies.forEach(c=>$('company').add(new Option(c.company.ticker+' · '+c.company.name,c.company.ticker)));S.models.forEach(m=>$('model').add(new Option(m.label,m.id)));$('company').value='WPM';$('model').value='metals_ewq';for(let id of ['company','model','period','frequency','cost'])$(id).onchange=update;let b=S.wpm_block_bootstrap;$('bootstrap').textContent=`Wheaton: the daily metals model reduces squared daily tracking error by ${pct(b.metals_ewq.sse_reduction)} versus the previous gold/silver model (12-month block-resampled 95% range ${pct(b.metals_ewq.range95[0])}–${pct(b.metals_ewq.range95[1])}). The market extension reduces it by ${pct(b.market_q.sse_reduction)} (${pct(b.market_q.range95[0])}–${pct(b.market_q.range95[1])}).`;window.companyResearch={summary:S,update,state:null};await update();let timer;addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(update,120);});}catch(e){$('status').textContent=e.message;console.error(e);}}
init();
