'use strict';
const $=id=>document.getElementById(id), fmt=(x,d=1)=>x==null?'—':(100*x).toFixed(d)+'%', pp=x=>x==null?'—':(100*x>=0?'+':'')+(100*x).toFixed(1)+' pp', num=x=>x==null?'—':x.toFixed(1)+'×';
let D,F,T,visible=new Set(),colors={},plots={},lastRisk=[],lastModel=[];
async function getData(){let r=await fetch('dashboard-data.json.gz');if(!r.ok)throw new Error('Research data could not be loaded.');if(!globalThis.DecompressionStream)throw new Error('This dashboard needs a browser with gzip decompression support.');let received=0;const progress=new TransformStream({transform(chunk,controller){received+=chunk.byteLength;$('status').textContent='Loading derived research data… '+(received/1e6).toFixed(1)+' MB';controller.enqueue(chunk);}});return JSON.parse(await new Response(r.body.pipeThrough(progress).pipeThrough(new DecompressionStream('gzip'))).text());}
function rows(model){const h=+$('horizon').value,lo=+$('start').value,hi=+$('end').value;return (model==='expost_vol_diagnostic'?(D.expost_windows||[]):D.window_details).filter(r=>r.model===model&&r.horizon_months===h&&visible.has(r.stock)&&+r.start.slice(0,4)>=lo&&+r.end.slice(0,4)<=hi);}
function median(a){if(!a.length)return null;a=[...a].sort((x,y)=>x-y);const m=a.length>>1;return a.length%2?a[m]:(a[m-1]+a[m])/2;}
function plot(id,points,xlabel,ylabel,options={}){
 const c=$(id),rect=c.getBoundingClientRect(),w=rect.width,h=rect.height,scale=devicePixelRatio||1;c.width=w*scale;c.height=h*scale;const ctx=c.getContext('2d');ctx.scale(scale,scale);ctx.clearRect(0,0,w,h);const pad={l:65,r:24,t:24,b:63},pw=w-pad.l-pad.r,ph=h-pad.t-pad.b;
 let vals=points.flatMap(p=>[p.x,p.y]);let low=options.rank?null:Math.min(0,...vals),high=options.rank?null:Math.max(0,...vals);let gap=Math.max(.05,(high-low)*.07);low-=gap;high+=gap;let xmin=options.rank?0:low,xmax=options.rank?1:high,ymin=options.rank?Math.min(-.05,...points.map(p=>p.y))-.02:low,ymax=options.rank?Math.max(.05,...points.map(p=>p.y))+.02:high;
 const X=x=>pad.l+(x-xmin)/(xmax-xmin)*pw,Y=y=>pad.t+(ymax-y)/(ymax-ymin)*ph;
 ctx.font='12px system-ui';ctx.fillStyle='#6b7f8a';ctx.strokeStyle='#e1e9ed';ctx.lineWidth=1;
 for(let k=0;k<=4;k++){let x=xmin+(xmax-xmin)*k/4,y=ymin+(ymax-ymin)*k/4;ctx.beginPath();ctx.moveTo(X(x),pad.t);ctx.lineTo(X(x),h-pad.b);ctx.stroke();ctx.beginPath();ctx.moveTo(pad.l,Y(y));ctx.lineTo(w-pad.r,Y(y));ctx.stroke();ctx.textAlign='center';ctx.fillText(fmt(x,0),X(x),h-pad.b+22);ctx.textAlign='right';ctx.fillText(fmt(y,0),pad.l-9,Y(y)+4);}
 ctx.strokeStyle='#6b7f8a';ctx.setLineDash([5,5]);ctx.beginPath();if(options.rank){ctx.moveTo(X(0),Y(0));ctx.lineTo(X(1),Y(0));}else{ctx.moveTo(X(low),Y(low));ctx.lineTo(X(high),Y(high));}ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#00294b';ctx.textAlign='left';ctx.fillText(options.rank?'Zero relative return':'Equal returns · slope 1',pad.l+9,pad.t+14);
 let rendered=[];for(const p of points){const x=X(p.x),y=Y(p.y);ctx.globalAlpha=.65;ctx.fillStyle=colors[p.stock]||'#005f9e';ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill();rendered.push({...p,px:x,py:y});}ctx.globalAlpha=1;ctx.textAlign='center';ctx.fillStyle='#00294b';ctx.fillText(xlabel,pad.l+pw/2,h-12);ctx.textAlign='left';ctx.fillText(ylabel,pad.l,14);if(!points.length){ctx.textAlign='center';ctx.fillText('No eligible observations for this selection',w/2,h/2);}
 plots[id]={points:rendered};c.onmousemove=e=>{const box=c.getBoundingClientRect(),x=e.clientX-box.left,y=e.clientY-box.top;let hit=null,dist=100;for(const p of rendered){let d=(p.px-x)**2+(p.py-y)**2;if(d<dist){hit=p;dist=d;}}const tip=$('tooltip');if(!hit){tip.style.display='none';return;}tip.innerHTML=`<b style="color:${colors[hit.stock]}">${hit.stock}</b> · ${hit.period}<br>${hit.xname}: ${fmt(hit.x)}<br>${hit.yname}: ${fmt(hit.y)}${hit.extra?'<br>'+hit.extra:''}`;tip.style.display='block';tip.style.left=Math.min(innerWidth-310,e.clientX+15)+'px';tip.style.top=Math.min(innerHeight-110,e.clientY+12)+'px';};c.onmouseleave=()=>$('tooltip').style.display='none';
}
function scatter(id,data,xname){let measure=$('measure').value;plot(id,data.map(r=>({stock:r.stock,x:r['replica_'+measure],y:r['stock_'+measure],period:r.start+' → '+r.end,xname,yname:'Stock return',extra:'Annualized gap: '+pp(r.stock_minus_replica_cagr)+(r.leverage!=null?' · '+r.leverage.toFixed(2)+'× gold'+(r.capped?' · capped, risk unmatched':' · future volatility used'):'')})),xname+(measure==='cagr'?' · annualized':' · total'),'Stock return');}
function table(id,heads,rows){$(id).innerHTML='<thead><tr>'+heads.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</tbody>';}
function update(){if(!D)return;lastRisk=rows($('risk').value);lastModel=rows($('model').value);$('risknote').textContent=$('risk').value==='expost_vol_diagnostic'?'LOOK-AHEAD DIAGNOSTIC. Future stock volatility chooses one constant gold exposure per window, capped at 3×. Quarterly fixed quantities and fees. This cannot be selected in advance; capped windows can remain risk mismatched.':'Exposure uses a trailing 36-month volatility ratio with a full-month information gap, capped at 3×. Realized volatility can differ. This is a past-only risk target.';scatter('riskchart',lastRisk,$('risk').value==='expost_vol_diagnostic'?'Future-volatility matched gold':'Volatility-targeted gold');scatter('modelchart',lastModel,'Replication portfolio');for(const [id,a]of[['riskcount',lastRisk],['modelcount',lastModel]])$(id).textContent=`${a.length.toLocaleString()} overlapping holding periods across ${new Set(a.map(r=>r.stock)).size} stocks. A rolling point is not an independent experiment.`;
 const spec=D.models.find(s=>s.id===$('model').value);$('modelnote').textContent=`${spec.label}. Trades every ${spec.rebalance_months} month(s). ${spec.options_kind==='none'?'No options.':'Option premiums and marks are hypothetical; silver volatility, where used, is an explicit model assumption.'}`;
 const tr=D.universe.filter(s=>visible.has(s.ticker)).map(s=>{let a=lastRisk.filter(r=>r.stock===s.ticker),b=lastModel.filter(r=>r.stock===s.ticker);return [`<span class="dot" style="background:${colors[s.ticker]}"></span> ${s.ticker}`,a.length,pp(median(a.map(r=>r.stock_minus_replica_cagr))),a.length?fmt(a.filter(r=>r.stock_minus_replica_cagr>0).length/a.length,0):'—',b.length,pp(median(b.map(r=>r.stock_minus_replica_cagr)))];});table('comparison',['Stock','Gold windows','Median stock − gold CAGR','Stock win rate','Model windows','Median stock − model CAGR'],tr);
 const path=D.paths.filter(r=>r.stock==='WPM'&&r.model===$('model').value&&+r.month.slice(0,4)>=+$('start').value&&+r.month.slice(0,4)<=+$('end').value);plot('wpmchart',path.map(r=>({stock:'WPM',x:r.replica_return,y:r.stock_return,period:r.month,xname:'Portfolio month',yname:'Wheaton month'})),'Portfolio monthly return','Wheaton monthly return');let mean=path.reduce((s,r)=>s+r.stock_return,0)/path.length;let sse=path.reduce((s,r)=>s+(r.stock_return-r.replica_return)**2,0),sst=path.reduce((s,r)=>s+(r.stock_return-mean)**2,0);$('wpmnote').textContent=path.length?`${path.length} months in the selected years. Tracking R² ${(1-sse/sst).toFixed(3)}. This scatter uses the ongoing simulation; holding-period charts start fresh accounts.`:'No Wheaton observations in the selected years.';fundamentals();}
function fundamentals(){if(!F)return;let k=$('signal').value,h=+$('fhorizon').value,col=`future_${h}m_gap`,a=F.observations.filter(r=>visible.has(r.stock)&&r[k+'_past_percentile']!=null&&r[col]!=null);plot('fchart',a.map(r=>({stock:r.stock,x:r[k+'_past_percentile'],y:r[col],period:'Filed '+r.filed,xname:'Rank among prior annual readings',yname:'Future stock − gold CAGR',extra:'Signal: '+(k==='net_margin'?fmt(r[k]):num(r[k]))})), 'Signal rank versus prior issuer history','Future stock − gold CAGR',{rank:true});let s=F.summary.find(r=>r.signal===k&&r.horizon_months===h);$('fresult').textContent=s?`Full sample, high versus low bucket: paired median difference ${pp(s.paired_median_high_minus_low)} across ${s.paired_stocks} issuers; ${s.high_observations} high and ${s.low_observations} low annual observations.${s.issuer_bootstrap_95?' Issuer-resampled 95% range: '+pp(s.issuer_bootstrap_95[0])+' to '+pp(s.issuer_bootstrap_95[1])+'.':' Too few paired issuers for a reported uncertainty interval.'} These small cohorts do not establish a reliable timing rule. The scatter follows stock toggles; these summary counts use the full study sample.`:'Insufficient eligible annual filings.';
 let joint=(F.joint_margin_pcf||[]).find(r=>r.horizon_months===h);$('jointresult').textContent=joint?`Joint high-margin / high-P-to-cash-flow observations: ${joint.high_margin_and_pcf_count} annual entries across ${joint.high_issuers} issuers at this horizon, with median future stock-minus-gold CAGR ${pp(joint.high_median_gap)}. This pooled bucket is descriptive and too small to establish a joint timing rule.`:'';table('current',['Stock','Annual period','Filed','Net margin','Prior margin rank','Annual P/E','Prior P/E rank','Annual P/OCF','Prior P/OCF rank'],F.current.filter(r=>visible.has(r.stock)).map(r=>[r.stock,r.fiscal_end,r.filed,fmt(r.net_margin),fmt(r.net_margin_past_percentile,0),num(r.current_pe),fmt(r.current_pe_past_percentile,0),num(r.current_pcf),fmt(r.current_pcf_past_percentile,0)]));}
function download(){const combined=[...lastRisk.map(r=>({...r,chart:'risk'})),...lastModel.map(r=>({...r,chart:'model'}))];if(!combined.length)return;let keys=Object.keys(combined[0]),csv=keys.join(',')+'\n'+combined.map(r=>keys.map(k=>JSON.stringify(r[k]??'')).join(',')).join('\n');let a=document.createElement('a'),u=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.href=u;a.download='gold-return-comparisons.csv';a.click();URL.revokeObjectURL(u);}
async function init(){try{[D,F,T]=await Promise.all([getData(),fetch('fundamentals.json').then(r=>r.json()),fetch('wpm_duration.json').then(r=>r.json())]);for(const s of D.universe){colors[s.ticker]=s.color;visible.add(s.ticker);let l=document.createElement('label');l.innerHTML=`<input type="checkbox" checked data-stock="${s.ticker}"><span class="dot" style="background:${s.color}"></span>${s.ticker}`;$('stocks').append(l);l.querySelector('input').onchange=e=>{e.target.checked?visible.add(s.ticker):visible.delete(s.ticker);update();};}for(const m of D.models.filter(m=>!m.id.startsWith('risk_matched'))){let o=new Option(m.label,m.id);$('model').add(o);}$('model').value='gold_silver_options_quarterly';let gold=D.common_summary.filter(r=>r.model==='gold_quarterly');$('meanfit').textContent=(gold.reduce((s,r)=>s+r.tracking_r2,0)/gold.length).toFixed(2);let q=D.horizons.filter(r=>r.model==='risk_matched_quarterly'&&r.horizon_months===60);$('losers').textContent=q.filter(r=>r.median_stock_minus_replica_cagr<0).length+' / '+q.length;let w=D.common_summary.find(r=>r.stock==='WPM'&&r.model==='gold_silver_options_quarterly');$('wpmfit').textContent=w.tracking_r2.toFixed(2);$('status').textContent=`${D.universe.length} stocks · ${D.models.length} candidate families · holdings through ${D.meta.cutoff} · price tests reach 15–17 years for most stocks`;
 for(const id of ['horizon','start','end','measure','risk','model','signal','fhorizon'])$(id).onchange=update;for(const [id,pred]of[['all',()=>true],['none',()=>false],['original',(s,i)=>i<7]])$(id).onclick=()=>{visible.clear();D.universe.forEach((s,i)=>{let on=pred(s,i);if(on)visible.add(s.ticker);document.querySelector(`[data-stock="${s.ticker}"]`).checked=on;});update();};table('duration',['Candidate','Start','Months','Tracking R²','Tracking error'],[...T.common_summary,...T.core_references_same_period].map(r=>[r.model.replaceAll('_',' '),r.start,r.months,r.tracking_r2.toFixed(3),fmt(r.tracking_error)]));$('download').onclick=download;let timer;addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(update,100);});update();window.goldResearch={data:D,fundamentals:F,update,rows};}catch(e){$('status').textContent=e.message;console.error(e);}}
init();
